package pkgfinal;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.ImageIo;
import javax.swing.JFileChooser;

//import javax.swing.JOptionPane;


public class MainMenu extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    int curRow = 0;
    String Reception; 
    String room2;
    String room3;
    String room4;
    String room5;
    String shop;
    String table;
    private BufferedImage bufImg;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
        }catch(Exception e){
            //System.out.println("Unable to load Driver");
        }
        
        try{
            String connectionUrl = "jdbc:mysql://127.0.0.1:3306/maindb";
            String connectionUser = "user";
            String connectionPassword = "password";
            con = DriverManager.getConnection(connectionUrl , connectionUser , connectionPassword);
        }catch(SQLException e){
            try {
                String connectionUrl = "jdbc:mysql://localhost:3306/maindb";
                String connectionUser = "user";
                String connectionPassword = "password"; 
                con = DriverManager.getConnection(connectionUrl , connectionUser , connectionPassword);
            } catch (SQLException ex) {
                 System.out.println("Unable to connect to database");
            } 
        }
        
        if(con!=null){
            try{
                stmt=con.createStatement();
            }catch(SQLException e){
                System.out.println("Unable to create statement");
            }
         }

        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPaneledit.setVisible(false);
        jPaneldelete.setVisible(false);
        jPanel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel6 = new javax.swing.JPanel();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPaneledit = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        mapbt = new javax.swing.JButton();
        login = new javax.swing.JButton();
        javax.swing.JButton jba1 = new javax.swing.JButton();
        jba2 = new javax.swing.JButton();
        jbe1 = new javax.swing.JButton();
        jbe2 = new javax.swing.JButton();
        jbe4 = new javax.swing.JButton();
        jbe3 = new javax.swing.JButton();
        jbd1 = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        jbb7 = new javax.swing.JButton();
        jbb1 = new javax.swing.JButton();
        jbb6 = new javax.swing.JButton();
        jbd5 = new javax.swing.JButton();
        jbb2 = new javax.swing.JButton();
        jbb5 = new javax.swing.JButton();
        jbb8 = new javax.swing.JButton();
        jbb3 = new javax.swing.JButton();
        jbb4 = new javax.swing.JButton();
        jbc2 = new javax.swing.JButton();
        jbc1 = new javax.swing.JButton();
        jbc3 = new javax.swing.JButton();
        jbd2 = new javax.swing.JButton();
        jbd3 = new javax.swing.JButton();
        jbd4 = new javax.swing.JButton();
        jbf1 = new javax.swing.JButton();
        jbf2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPaneldelete = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        gmap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 5, 5));
        setBounds(new java.awt.Rectangle(0, 0, 975, 478));
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(1024, 640));
        setMinimumSize(new java.awt.Dimension(975, 520));
        setPreferredSize(new java.awt.Dimension(1000, 520));
        getContentPane().setLayout(null);

        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 582, 397);

        jPaneledit.setMinimumSize(new java.awt.Dimension(690, 480));

        jButton8.setText("Save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reception", "room2", "room3", "room4", "room5", "shop" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton9.setText("Cancel");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jScrollPane2.setViewportView(jTextPane2);

        jLabel2.setText("Please enter below item name");

        jLabel3.setText("Please enter below item picture");

        jLabel4.setText("Please enter below item information");

        jButton6.setText("search image");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneleditLayout = new javax.swing.GroupLayout(jPaneledit);
        jPaneledit.setLayout(jPaneleditLayout);
        jPaneleditLayout.setHorizontalGroup(
            jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneleditLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneleditLayout.createSequentialGroup()
                        .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneleditLayout.createSequentialGroup()
                                .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneleditLayout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPaneleditLayout.setVerticalGroup(
            jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneleditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneleditLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneleditLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneleditLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPaneledit);
        jPaneledit.setBounds(0, 0, 690, 480);

        mapbt.setText("MAP");
        mapbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapbtActionPerformed(evt);
            }
        });
        getContentPane().add(mapbt);
        mapbt.setBounds(690, 450, 95, 30);

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(880, 450, 95, 30);

        jba1.setText("jButton2");
        jba1.setContentAreaFilled(false);
        jba1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jba1ActionPerformed(evt);
            }
        });
        getContentPane().add(jba1);
        jba1.setBounds(30, 390, 30, 20);

        jba2.setText("jButton2");
        jba2.setContentAreaFilled(false);
        jba2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jba2ActionPerformed(evt);
            }
        });
        getContentPane().add(jba2);
        jba2.setBounds(120, 360, 50, 40);

        jbe1.setText("jButton2");
        jbe1.setContentAreaFilled(false);
        jbe1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbe1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbe1);
        jbe1.setBounds(500, 280, 50, 40);

        jbe2.setText("jButton2");
        jbe2.setContentAreaFilled(false);
        jbe2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbe2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbe2);
        jbe2.setBounds(490, 220, 50, 40);

        jbe4.setText("jButton2");
        jbe4.setContentAreaFilled(false);
        jbe4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbe4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbe4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbe4);
        jbe4.setBounds(640, 270, 50, 40);

        jbe3.setText("jButton2");
        jbe3.setContentAreaFilled(false);
        jbe3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbe3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbe3);
        jbe3.setBounds(630, 220, 50, 40);

        jbd1.setText("jButton2");
        jbd1.setContentAreaFilled(false);
        jbd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbd1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbd1);
        jbd1.setBounds(490, 140, 50, 40);

        contact.setText("CONTACT");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact);
        contact.setBounds(785, 450, 95, 30);

        jbb7.setText("jButton2");
        jbb7.setContentAreaFilled(false);
        jbb7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb7);
        jbb7.setBounds(90, 220, 50, 40);

        jbb1.setText("jButton2");
        jbb1.setContentAreaFilled(false);
        jbb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb1);
        jbb1.setBounds(30, 280, 30, 20);

        jbb6.setText("jButton2");
        jbb6.setContentAreaFilled(false);
        jbb6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb6);
        jbb6.setBounds(150, 270, 50, 40);

        jbd5.setText("jButton2");
        jbd5.setContentAreaFilled(false);
        jbd5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbd5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbd5);
        jbd5.setBounds(530, 80, 50, 40);

        jbb2.setText("jButton2");
        jbb2.setContentAreaFilled(false);
        jbb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb2);
        jbb2.setBounds(40, 180, 40, 30);

        jbb5.setText("jButton2");
        jbb5.setContentAreaFilled(false);
        jbb5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb5);
        jbb5.setBounds(150, 170, 50, 40);

        jbb8.setText("jButton2");
        jbb8.setContentAreaFilled(false);
        jbb8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb8);
        jbb8.setBounds(100, 130, 50, 40);

        jbb3.setText("jButton2");
        jbb3.setContentAreaFilled(false);
        jbb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb3);
        jbb3.setBounds(50, 80, 40, 30);

        jbb4.setText("jButton2");
        jbb4.setContentAreaFilled(false);
        jbb4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbb4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbb4);
        jbb4.setBounds(120, 0, 50, 40);

        jbc2.setText("jButton2");
        jbc2.setContentAreaFilled(false);
        jbc2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbc2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbc2);
        jbc2.setBounds(320, 80, 50, 40);

        jbc1.setText("jButton2");
        jbc1.setContentAreaFilled(false);
        jbc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbc1);
        jbc1.setBounds(310, 170, 50, 40);

        jbc3.setText("jButton2");
        jbc3.setContentAreaFilled(false);
        jbc3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbc3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbc3);
        jbc3.setBounds(320, 0, 50, 40);

        jbd2.setText("jButton2");
        jbd2.setContentAreaFilled(false);
        jbd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbd2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbd2);
        jbd2.setBounds(530, -10, 50, 40);

        jbd3.setText("jButton2");
        jbd3.setContentAreaFilled(false);
        jbd3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbd3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbd3);
        jbd3.setBounds(590, 50, 50, 40);

        jbd4.setText("jButton2");
        jbd4.setContentAreaFilled(false);
        jbd4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbd4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbd4);
        jbd4.setBounds(600, 120, 50, 40);

        jbf1.setText("jButton2");
        jbf1.setContentAreaFilled(false);
        jbf1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbf1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbf1);
        jbf1.setBounds(580, 380, 50, 40);

        jbf2.setText("jButton2");
        jbf2.setContentAreaFilled(false);
        jbf2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbf2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbf2);
        jbf2.setBounds(340, 290, 50, 40);

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("WELCOME");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setMaximumSize(new java.awt.Dimension(270, 126));
        jTextArea2.setPreferredSize(new java.awt.Dimension(270, 126));
        jScrollPane7.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4)))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(690, 0, 290, 450);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("ΛΕΩΦΟΡΕΙΑ \n\n035, 049, 227, 500, 815, \n838, 914, Β18, Γ18 \n\nΤΡΟΛΛΕΫ 21 \n\nΜΕΤΡΟ \n\nγραμμή 3 (σταθμός ΚΕΡΑΜΙΚΟΣ)\n \nΗΛΕΚΤΡΙΚΟΣ ΣΙΔΗΡΟΔΡΟΜΟΣ\n \nσταθμός ΠΕΤΡΑΛΩΝΩΝ");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/map.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(690, 0, 290, 450);

        jTextPane1.setEditable(false);
        jTextPane1.setText("Για οποιαδήποτε πρόσθετη πληροφορία ή διευκρίνιση, μπορείτε να επικοινωνείτε μέσω e-mail στη διεύθυνση sales-shop@benaki.gr. ή τηλεφωνικά στο 0030 210 3671000 καθημερινά 09:00-17:00 εκτός Τρίτης. \n\nΩράρια Πωλητηρίων\n\nΠωλητήριο Κουμπάρη 1\nΔευτέρα, Τετάρτη, Παρασκευή: 9.00-17.00, Πέμπτη: 9.00-20.00, Σάββατο: 9.00-20.00, Κυριακή: 9.00-15.00, Τρίτη: Kλειστά \nΤηλ.0030 210 3671000-Fax: 0030 2103671063 ");
        jTextPane1.setToolTipText("");
        jTextPane1.setEnabled(false);
        jScrollPane3.setViewportView(jTextPane1);

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(690, 0, 290, 450);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton1.setText("ΟΚ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ΑΚΥΡΟ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("PLEASE ENTER THE PASSWORD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 99, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(690, 0, 290, 450);

        jPanel5.setMinimumSize(new java.awt.Dimension(290, 450));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("ADMINISTRATION PANEL");

        jButton5.setText("EDIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(690, 0, 290, 450);

        jPaneldelete.setMinimumSize(new java.awt.Dimension(690, 480));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reception", "room2", "room3", "room4", "room5", "shop" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Cancel");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneldeleteLayout = new javax.swing.GroupLayout(jPaneldelete);
        jPaneldelete.setLayout(jPaneldeleteLayout);
        jPaneldeleteLayout.setHorizontalGroup(
            jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldeleteLayout.createSequentialGroup()
                .addGroup(jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneldeleteLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneldeleteLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPaneldeleteLayout.setVerticalGroup(
            jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldeleteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(jPaneldelete);
        jPaneldelete.setBounds(0, 0, 690, 480);

        gmap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/Untitled picture10.png"))); // NOI18N
        gmap.setText("jLabel1");
        getContentPane().add(gmap);
        gmap.setBounds(0, 0, 690, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jba1ActionPerformed
        // TODO add your handling code here:
        if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from Reseption where idpic=2;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        
    }//GEN-LAST:event_jba1ActionPerformed

    private void jbd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbd5ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room4 where idpic=3;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbd5ActionPerformed

    private void jba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jba2ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from Reseption where idpic=1;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jba2ActionPerformed

    private void jbb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb8ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room2 where idpic=6;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbb8ActionPerformed

    private void jbd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbd2ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room4 where idpic=5;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                  jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbd2ActionPerformed

    private void jbd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbd3ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room4 where idpic=4;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                  jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbd3ActionPerformed

    private void jbc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbc3ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room3 where idpic=1;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbc3ActionPerformed

    private void jbd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbd4ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room4 where idpic=2;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbd4ActionPerformed

    private void jbf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbf1ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from shop where idshop=1;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbf1ActionPerformed

    private void jbd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbd1ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room4 where idpic=1;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbd1ActionPerformed

    private void jbe4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbe4ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room5 where idpic=4;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("capture"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbe4ActionPerformed

    private void jbc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbc2ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room3 where idpic=2;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbc2ActionPerformed

    private void jbc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbc1ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room3 where idpic=3;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbc1ActionPerformed

    private void jbb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb1ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room2 where idpic=1;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbb1ActionPerformed

    private void jbb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb4ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room2 where idpic=8;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbb4ActionPerformed

    private void jbe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbe2ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room5 where idpic=1;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("capture"));
                    
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbe2ActionPerformed

    private void jbb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb3ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room2 where idpic=7;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbb3ActionPerformed

    private void jbf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbf2ActionPerformed

    private void jbe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbe3ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room5 where idpic=2;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){ 
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("capture"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbe3ActionPerformed

    private void jbb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb2ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room2 where idpic=4;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbb2ActionPerformed

    private void jbb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb7ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room2 where idpic=3;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbb7ActionPerformed

    private void jbe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbe1ActionPerformed

    private void jbb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb6ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room5 where idpic=3;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("capture"));
                    jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbb6ActionPerformed

    private void jbb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbb5ActionPerformed
if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from room2 where idpic=5;");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        if(rs!=null){
            try{
                while(rs.next()){
                    jTextField4.setText(rs.getString("caption"));
                   jTextArea2.setText(rs.getNString("info"));
                   // jLabel5 = (JLabel) rs.getBlob("img");
                    InputStream in = rs.getBinaryStream("img");
                    bufImg = ImageIO.read(in);
                    jLabel5.setIcon(new ImageIcon(bufImg));
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbb5ActionPerformed

    private void mapbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapbtActionPerformed
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_mapbtActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_contactActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_loginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (String.copyValueOf(jPasswordField1.getPassword()).equals("12")) { //Process the password.
          jPanel5.setVisible(true);
          jPanel3.setVisible(false);
          contact.setVisible(false);
          mapbt.setVisible(false);
          login.setVisible(false);
          jPanel6.setVisible(false);
       }
       jPasswordField1.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel2.setVisible(false);
        jPanel4.setVisible(true);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel1.setVisible(false);
        jPanel4.setVisible(true);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPaneledit.setVisible(true);
        jPaneldelete.setVisible(false);
        jPanel5.setVisible(true);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPanel5.setVisible(false);
        jPanel4.setVisible(true);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPaneledit.setVisible(false);
        jPaneldelete.setVisible(false);
        contact.setVisible(true);
        mapbt.setVisible(true);
        login.setVisible(true);  
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String sql;
        sql = "update "+jComboBox1.getSelectedItem()+" set caption='"+jTextPane2.getText()+"',info='"+jTextArea4.getText()+"',img='"+String.valueOf(jComboBox2.getSelectedItem())+";";
        
        if(stmt!=null){
            try{
                stmt.executeUpdate(sql);
            }catch(SQLException e){
                
            }
            
        }
  
        
      
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jPanel6.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
          int o=jFileChooser1.showOpenDialog(this);
        if(o==JFileChooser.APPROVE_OPTION){
        File f=jFileChooser1.getSelectedFile();
        jLabel6.setIcon(new ImageIcon(""+f));
        jPanel6.setVisible(false);
        }
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contact;
    private javax.swing.JLabel gmap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPaneldelete;
    private javax.swing.JPanel jPaneledit;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton jba2;
    private javax.swing.JButton jbb1;
    private javax.swing.JButton jbb2;
    private javax.swing.JButton jbb3;
    private javax.swing.JButton jbb4;
    private javax.swing.JButton jbb5;
    private javax.swing.JButton jbb6;
    private javax.swing.JButton jbb7;
    private javax.swing.JButton jbb8;
    private javax.swing.JButton jbc1;
    private javax.swing.JButton jbc2;
    private javax.swing.JButton jbc3;
    private javax.swing.JButton jbd1;
    private javax.swing.JButton jbd2;
    private javax.swing.JButton jbd3;
    private javax.swing.JButton jbd4;
    private javax.swing.JButton jbd5;
    private javax.swing.JButton jbe1;
    private javax.swing.JButton jbe2;
    private javax.swing.JButton jbe3;
    private javax.swing.JButton jbe4;
    private javax.swing.JButton jbf1;
    private javax.swing.JButton jbf2;
    private javax.swing.JButton login;
    private javax.swing.JButton mapbt;
    // End of variables declaration//GEN-END:variables
}
